# -*- coding: utf-8 -*-
"""PhyshingURLdetection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AiLKwWoEZHNuL0bzuBcJNH6w10IAda_X
"""

# Installation libs
!pip install -q scikit-learn pandas numpy matplotlib seaborn lightgbm tldextract joblib

from google.colab import files
import io
import pandas as pd

# clique et choisis phishing_site_urls.csv depuis ton PC
uploaded = files.upload()


df = pd.read_csv(io.BytesIO(uploaded['phishing_site_urls.csv']), low_memory=False)
print("Loaded from upload:", df.shape)
df.head()

# ---- Cellule : map labels en binaire et distribution ----
import pandas as pd
# df vient de ton upload ; on inspecte les colonnes affichées ("URL","Label" d'après ton output)
print(df.columns.tolist())
# On normalise les noms si nécessaire
df = df.rename(columns={df.columns[0]:'url', df.columns[1]:'label_raw'})
# map simple : 'bad' -> 1, tout le reste -> 0 (adaptable)
df['label'] = df['label_raw'].apply(lambda x: 1 if str(x).strip().lower()=='bad' else 0)
print("Total rows:", len(df))
print("Distribution labels (counts):")
print(df['label'].value_counts())
print("Distribution normalized:")
print(df['label'].value_counts(normalize=True))
df[['url','label_raw','label']].head(6)

# ---- Cellule : créer un échantillon stratifié ----
from sklearn.model_selection import train_test_split

# Taille d'échantillon à utiliser pour l'entraînement (ajuste selon RAM)
SAMPLE_SIZE = 120000  # ex : 120k ; si tu veux plus, augmente, mais attention mémoire
n_total = len(df)
if SAMPLE_SIZE >= n_total:
    df_sample = df.copy()
else:
    # stratified sample: on extrait SAMPLE_SIZE en respectant proportions
    frac = SAMPLE_SIZE / n_total
    # pandas >= 1.1 a sample(frac=...) ; pour stratify, on fait groupby.sample si pandas >= 1.1
    try:
        df_sample = df.groupby('label', group_keys=False).sample(frac=frac, random_state=42)
    except Exception as e:
        # fallback: use sklearn train_test_split by label groups
        df_sample, _ = train_test_split(df, train_size=SAMPLE_SIZE, stratify=df['label'], random_state=42)
print("Sample shape:", df_sample.shape)
print(df_sample['label'].value_counts(normalize=True))

# ---- Cellule : fonctions lexicales (réutilisables) ----
import re, math
from collections import Counter
import tldextract
import numpy as np

def has_ip(url):
    m = re.search(r'//(\d{1,3}\.){3}\d{1,3}', url)
    return 1 if m else 0

def str_entropy(s):
    if not s:
        return 0.0
    counts = Counter(s)
    probs = [c/len(s) for c in counts.values()]
    return -sum(p*math.log2(p) for p in probs)

def extract_lexical_features(url):
    try:
        ext = tldextract.extract(url)
        domain = ext.domain + ('.' + ext.suffix if ext.suffix else '')
    except:
        domain = ''
    features = {}
    features['url_len'] = len(url)
    features['domain_len'] = len(domain)
    features['num_dots'] = url.count('.')
    features['num_slash'] = url.count('/')
    features['num_params'] = url.count('?') + url.count('&')
    features['has_at'] = 1 if '@' in url else 0
    features['has_dash'] = 1 if '-' in domain else 0
    features['has_ip'] = has_ip(url)
    features['count_digits'] = sum(c.isdigit() for c in url)
    features['domain_entropy'] = str_entropy(domain)
    return features

# Appliquer sur l'échantillon (cela prend un peu de temps mais reste rapide)
lex_df = df_sample['url'].apply(extract_lexical_features).apply(pd.Series)
df_sample = pd.concat([df_sample.reset_index(drop=True), lex_df.reset_index(drop=True)], axis=1)
df_sample.head()

# ---- Cellule : TF-IDF char n-grams ----
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer(analyzer='char', ngram_range=(3,5), max_features=3000)  # ajustable
X_tfidf = vectorizer.fit_transform(df_sample['url'])
print("TF-IDF shape:", X_tfidf.shape)

# ---- Cellule : assembler et split train/test ----
import scipy.sparse as sp
lex_features = ['url_len','domain_len','num_dots','num_slash','num_params','has_at','has_dash','has_ip','count_digits','domain_entropy']
X_lex = df_sample[lex_features].fillna(0).values
X = sp.hstack([X_tfidf, sp.csr_matrix(X_lex)]).tocsr()
y = df_sample['label'].astype(int).values

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)
print("Train / Test shapes:", X_train.shape, X_test.shape)

# ---- Cellule : entraîner LightGBM ----
!pip install -q lightgbm
from lightgbm import LGBMClassifier
from sklearn.metrics import classification_report, roc_auc_score, confusion_matrix

lgb = LGBMClassifier(n_estimators=300, random_state=42)
lgb.fit(X_train, y_train)
y_pred = lgb.predict(X_test)
y_prob = lgb.predict_proba(X_test)[:,1]

print("Classification report:")
print(classification_report(y_test, y_pred))
print("ROC-AUC:", roc_auc_score(y_test, y_prob))
print("Confusion matrix:\n", confusion_matrix(y_test, y_pred))

# ---- Cellule : sauvegarder bundle (si LightGBM / TF-IDF utilisé) ----
import joblib
model_bundle = {
    'model': lgb,                # ou clf pour SGD
    'vectorizer': vectorizer,    # si TF-IDF
    'lex_features': lex_features
}
joblib.dump(model_bundle, 'phish_model_bundle.joblib')
print("Model bundle saved: phish_model_bundle.joblib")
# copier sur Drive si tu montes Drive :
# !cp phish_model_bundle.joblib /content/drive/MyDrive/

# ---- Cellule : fonction utilitaire prédiction (pour LightGBM + TF-IDF) ----
import numpy as np
import scipy.sparse as sp
def predict_url(url, bundle):
    vec = bundle['vectorizer']
    model = bundle['model']
    lex_feats = bundle['lex_features']

    url_norm = url.strip().lower()
    x_tfidf = vec.transform([url_norm])
    lex = extract_lexical_features(url_norm)
    X_lex_single = np.array([[lex[f] for f in lex_feats]])
    X_single = sp.hstack([x_tfidf, sp.csr_matrix(X_lex_single)]).tocsr()

    prob_phish = float(model.predict_proba(X_single)[:,1][0])  # prob phishing
    label = "phishing" if prob_phish >= 0.5 else "legit"

    # calcul de la "confiance" selon le label prédit
    confidence = prob_phish if label == "phishing" else 1 - prob_phish

    return f"{label} ({confidence*100:.1f}% confident)"

#contenu selon num de ligne
i = 389542
print(f"URL: {df.iloc[i]['url']}  |  Label: {df.iloc[i]['label']}")

# test rapide
bundle = joblib.load('phish_model_bundle.joblib')
print(predict_url("https://www.google.com/search?q=quantum+computer&sca_esv=7ea9874e2de762c7&sxsrf=AE3TifPp-4Ww51i7kF2cz_AmxPnA6n2avw%3A1760796682713&ei=CqDzaKeqK4fU7M8PiZDUgQg&udm=2&oq=quantu&gs_lp=Egxnd3Mtd2l6LXNlcnAaAhgCIgZxdWFudHUqAggBMhIQIxjwBRiABBgTGCcYyQIYigUyEBAjGPAFGIAEGCcYyQIYigUyChAjGPAFGCcYyQIyDRAAGIAEGLEDGEMYigUyCBAAGIAEGLEDMggQLhiABBixAzIFEAAYgAQyBRAAGIAEMgUQABiABDIOEAAYgAQYsQMYgwEYigVIlBdQAFiUBnAAeAGQAQCYAVqgAbUDqgEBNrgBAcgBAPgBAZgCBqACwQTCAgoQIxiABBgnGIoFwgIOEC4YgAQYxwEYjgUYrwHCAg4QLhiABBixAxjRAxjHAcICCxAAGIAEGLEDGIMBwgILEC4YgAQY0QMYxwHCAhEQLhiABBixAxjRAxiDARjHAcICChAAGIAEGEMYigXCAhMQLhiABBixAxjRAxhDGMcBGIoFwgIOEAAYgAQYkgMYuAQYigXCAgsQABiABBiSAxiKBcICCBAAGIAEGMkDwgIREC4YgAQYsQMYpAMYqAMYiwPCAhIQABiABBixAxhDGIoFGAoYiwPCAg0QLhiABBjRAxjHARgKmAMAkgcDNC4yoAedV7IHAzQuMrgHwQTCBwUzLTMuM8gHdQ&sclient=gws-wiz-serp", bundle))

print(predict_url("https://www.youtube.com/watch?v=H8W9oMNSuwo&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ", bundle))

print(predict_url("https://stackoverflow.com/questions/56604151/how-to-extract-multiple-objects-from-an-image-using-python-opencv", bundle))

print(predict_url("www.dghjdgf.com/paypal.co.uk/cycgi-bin/webscrcmd=_home-customer&nav=1/loading.php", bundle))

print(predict_url("premierpaymentprocessing.com/includes/boleto-2via-07-2012.php", bundle))